#template: "Hello, %s!"
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    org.example: DEBUG
  appenders:
    - type: console
    - type: file
      currentLogFilename: logs/application.log
      archivedLogFilenamePattern: logs/application-%d.log.gz
      archivedFileCount: 5
      logFormat: "%d{ISO8601} [%thread] %-5level %logger - %msg%n"